# Generated by Django 5.2.6 on 2025-09-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='verdict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
