# Generated by Django 5.2.6 on 2025-09-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_article_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('id_number', models.IntegerField()),
                ('portfolio', models.CharField(max_length=100)),
            ],
        ),
    ]
