# Generated by Django 5.2.6 on 2025-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='portfolio',
            field=models.JSONField(),
        ),
    ]
