# Generated by Django 5.2.6 on 2025-09-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_alter_customer_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
    ]
