# Generated by Django 5.2.6 on 2025-09-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_remove_customer_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.TextField()),
                ('verdict', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
