# Generated by Django 5.2.6 on 2025-09-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_filing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
