# Generated by Django 5.2.6 on 2025-09-21 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='portfolio',
        ),
        migrations.CreateModel(
            name='PortfolioOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='interface.portfoliocategory')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='interface.portfoliooption'),
        ),
    ]
