# Generated by Django 5.2.6 on 2025-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_portfoliocategory_remove_customer_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('assets', models.TextField(help_text='Comma-separated list of assets, e.g. Bitcoin, USD, Gold')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfoliooption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.DeleteModel(
            name='PortfolioOption',
        ),
        migrations.AddField(
            model_name='customer',
            name='portfolio',
            field=models.JSONField(default='[]', help_text='List of portfolio names'),
        ),
    ]
